/******************************************************************************
 * File: nd_top_wrapper.sv
 *
 * Company: IC Verimeter
 *
 * Author: icshunt.help@gmail.com
 *
 * Description: Top-level wrapper module that instantiates the bus interface and
 *              connects the DUT to the verification environment.
 *
 * Created: July 25, 2026 (icshunt.help@gmail.com)
 *
 * Copyright (c) 2026 IC Verimeter
 * Licensed under the MIT license. See LICENSE file in the project root for details.
 ******************************************************************************/

`ifndef ND_TOP_WRAPPER_SV
`define ND_TOP_WRAPPER_SV

//Module: nd_top_wrapper
//Top-level wrapper module that instantiates the bus interface and
//connects the DUT to the verification environment.
module nd_top_wrapper;

  //Variable: clk
  //System clock generated by the testbench
  logic clk;

  //Variable: rst_n
  //Active-low reset signal
  logic rst_n;

  //Variable: bus_if
  //Bus interface instance connecting DUT to the verification environment
  nd_bus_if bus_if (.clk(clk), .rst_n(rst_n));

  //process: clk_gen
  //Generates the system clock.
  initial begin : clk_gen
    clk = 0;
    forever #5 clk = ~clk;
  end

  //process: rst_gen
  //Generates the active-low reset signal.
  initial begin : rst_gen
    rst_n = 0;
    #20 rst_n = 1;
  end

endmodule : nd_top_wrapper

`endif // ND_TOP_WRAPPER_SV
